sass:
  style: compressed
  sass_dir: ./assets/styles
  
collections:
  documentos:
    output: true
  
defaults:
  -
    scope:
      path: ""
      type: documentos
    values:
      layout: default